### ISSUE TITLE
Missing  character "Ə"

### ISSUE THREAD

**Issue by jamal-ali1989** [canonical/Ubuntu-Sans-fonts#120]
I have tested this with practically every latest ubuntu font. The character İ am referring to is this one: https://en.wikipedia.org/wiki/%C6%8F

Ubuntu fonts do have this character's uppercase version, which works fine.
However, when I type its lowercase version, I either get an unknown character symbol or I get its capital form.
Is the lowercare version also going to get added in the future? There are a few languages that use this character.
The missing character's unicode value U0259 (lowercase version). However, it automatically defaults to U018F (uppercase version) specifically on Ubuntu fonts.

**Comment by djrrb** [comment]
Thank you for reporting this! Yes, this is a known issue with Ə and a handful of other characters. It is documented here: https://github.com/canonical/Ubuntu-Sans-fonts/issues/103

I don’t have any information about if/when the lowercase will be added. If it’s okay with you I’ll close this issue but you are welcome to add a comment in #103 so that folks tracking that issue can see that there is demand for this coverage. Cheers!

**Comment by jamal-ali1989** [comment]
Thank you, of course you can close the issue. However, does "not planned" mean that they are NOT going to add it or that it is not a priority?

**Comment by djrrb** [comment]
Sorry about that, I didn’t mean to imply anything about priorities here...was simply trying to mark it as a duplicate. Thank you for posting in the other thread!
