### ISSUE TITLE
Interpolation error on eshreversedloop

### ISSUE THREAD

**Issue by guidoferreyra** [canonical/Ubuntu-Sans-fonts#95]
A weird interpolation error it’s happening on, at first glance I couldn’t spot the problem

![Screen Shot 2023-06-27 at 17 30 12](https://github.com/canonical/Ubuntu-fonts/assets/1755590/11bcdd4b-3518-4577-851f-695afeedc252)

**Comment by djrrb** [comment]
Wow, this is very bizarre. Nothing unusual about outlines, and they seem totally fine in the UFOs. Error persists if start point is changed to the bottom of loop. Will require further investigation.

**Comment by djrrb** [comment]
Error persists in CFF2!

<img width="1840" alt="Screenshot 2023-06-28 at 12 07 03 AM" src="https://github.com/canonical/Ubuntu-fonts/assets/6578861/cf161409-3289-467b-be63-3c2de1ced56d">

**Comment by djrrb** [comment]
The Condensed Thin Italic UFO was correct, but it was missing from the latest designspace. 

Because this is a significant omission, I am going to patch the 0.869 fonts before we jump to 1.0.

<img width="1840" alt="Screenshot 2023-06-28 at 8 39 13 AM" src="https://github.com/canonical/Ubuntu-fonts/assets/6578861/3cb9cff4-3aa4-4521-a460-7f940dbb64fb">
